"use client";

import { useState, useTransition } from "react";
import { useRouter } from "next/navigation";
import { SendHorizontal } from "lucide-react";
import { startConversationAction } from "./actions";
import { Textarea } from "@/components/ui/textarea";
import { Button } from "@/components/ui/button";
import { Alert, AlertDescription } from "@/components/ui/alert";
import { AIThinkingIndicator } from "@/components/shared/ai-chat";

const MAX_LENGTH = 4000;

/** Starts a brand-new conversation; on success, navigates to its own thread page (where the real assistant reply — already generated by the time this resolves — is immediately visible). */
export function NewConversationForm({ organizationId }: { organizationId: string }) {
  const [message, setMessage] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [pending, startTransition] = useTransition();
  const router = useRouter();

  function handleSubmit() {
    if (!message.trim()) return;
    setError(null);
    startTransition(async () => {
      const result = await startConversationAction({ organizationId, message });
      if (result.error) {
        setError(result.error);
        return;
      }
      if (result.conversation) router.push(`/organizations/${organizationId}/assistant/${result.conversation.id}`);
    });
  }

  return (
    <div className="flex flex-col gap-3">
      <Textarea
        value={message}
        onChange={(e) => setMessage(e.target.value.slice(0, MAX_LENGTH))}
        placeholder="Ask the Alpha OS assistant a question…"
        aria-label="New message"
        rows={3}
        disabled={pending}
        onKeyDown={(e) => {
          if (e.key === "Enter" && !e.shiftKey) {
            e.preventDefault();
            handleSubmit();
          }
        }}
      />
      <div className="flex items-center justify-between gap-3">
        <span className="text-xs text-muted-foreground">{message.length}/{MAX_LENGTH}</span>
        <Button data-testid="start-conversation-button" onClick={handleSubmit} disabled={pending || !message.trim()}>
          <SendHorizontal className="size-4" aria-hidden="true" />
          Start conversation
        </Button>
      </div>
      {pending ? <AIThinkingIndicator /> : null}
      {error ? (
        <Alert variant="destructive">
          <AlertDescription>{error}</AlertDescription>
        </Alert>
      ) : null}
    </div>
  );
}
